CREATE DATABASE IF NOT EXISTS chat_ui;
USE chat_ui;
CREATE TABLE IF NOT EXISTS messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  color VARCHAR(20) DEFAULT '#e74c3c',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
